version: '3'
services:
  app:
    container_name: docker-fitman
    restart: always
    build: .
    ports:
    - '3000:3000'
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - '27017:27017'
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: 'Fitman_Database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - '3306:3306'
